LachlanMcKee/gsonpath

gsonpath-compiler/src/main/java/gsonpath/GsonProcessor.java, gsonpath-compiler/src/main/java/gsonpath/generator/BaseAdapterGenerator.java, gsonpath-compiler/src/main/java/gsonpath/generator/GsonFieldTree.java, gsonpath-compiler/src/main/java/gsonpath/generator/adapter/AutoGsonAdapterGenerator.java, gsonpath-compiler/src/main/java/gsonpath/generator/streamer/GsonArrayStreamerGenerator.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/ProcessorErrorsTest.java, gsonpath-compiler/src/test/resources/adapter/auto/processor_errors/TestDuplicateFieldError.java, gsonpath-compiler/src/test/resources/adapter/auto/processor_errors/TestInvalidFieldPathError.java, gsonpath-compiler/src/test/resources/adapter/auto/processor_errors/TestInvalidFieldTypeError.java
Improves the error messaging within the annotation processor. #21
=> Improved processor messaging and added better error handling

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/AutoGsonAdapterGenerator.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/DefaultsTest.java, gsonpath-compiler/src/test/resources/adapter/auto/defaults/TestDefaultsConfig.java, gsonpath-compiler/src/test/resources/adapter/auto/defaults/TestDefaultsOverrideInheritanceModel.java, gsonpath-compiler/src/test/resources/adapter/auto/defaults/TestDefaultsOverrideInheritanceModel_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/defaults/TestDefaultsUseInheritanceModel.java, gsonpath-compiler/src/test/resources/adapter/auto/defaults/TestDefaultsUseInheritanceModel_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/delimiter/custom/TestCustomDelimiter.java, gsonpath-compiler/src/test/resources/adapter/auto/delimiter/multiple/TestMultipleDelimiters.java, gsonpath-compiler/src/test/resources/adapter/auto/empty/invalid_fields/TestInvalidFields.java, gsonpath-compiler/src/test/resources/adapter/auto/naming_policy/identity/TestNamePolicyIdentity.java, gsonpath-compiler/src/test/resources/adapter/auto/naming_policy/lowercase_dashes/TestNamePolicyLowerCaseDashes.java, gsonpath-compiler/src/test/resources/adapter/auto/naming_policy/lowercase_underscores/TestNamePolicyLowerCaseUnderscores.java, gsonpath-compiler/src/test/resources/adapter/auto/naming_policy/upper_camel_case/TestNamePolicyUpperCamelCase.java, gsonpath-compiler/src/test/resources/adapter/auto/naming_policy/upper_camel_case_spaces/TestNamePolicyUpperCamelCaseSpaces.java, gsonpath-compiler/src/test/resources/adapter/auto/serialize_nulls/TestSerializeNulls.java, gsonpath/src/main/java/gsonpath/AutoGsonAdapter.java, gsonpath/src/main/java/gsonpath/FlattenDelimiter.java, gsonpath/src/main/java/gsonpath/GsonFieldValidationType.java, gsonpath/src/main/java/gsonpath/GsonPathDefaultConfiguration.java, gsonpath/src/main/java/gsonpath/GsonPathFieldNamingPolicy.java, gsonpath/src/main/java/gsonpath/InheritableBoolean.java
Created a mechanism to create a set of default values for the AutoGsonAdapter which overrides the defautls within the AutoGsonAdapter.
The benefits of this is that developers can specify defaults that they prefer.
=> Added a feature to set AutoGsonAdapter default values globally.

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/AutoGsonAdapterGenerator.java, gsonpath-compiler/src/test/resources/adapter/auto/field_policy/validate_explicit_non_null/TestValidateExplicitNonNull.java, gsonpath-compiler/src/test/resources/adapter/auto/field_policy/validate_explicit_non_null/TestValidateExplicitNonNull_GsonTypeAdapter.java
=> Fixed behaviour surrounding GsonFieldValidationType and primitives

gsonpath/src/main/java/gsonpath/JsonFieldMissingException.java
=> Changed JsonFieldMissingException parent class to be JsonParseException

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/ModelInterfaceGenerator.java, gsonpath-compiler/src/test/java/gsonpath/NonNull.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/InterfaceTest.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritance.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritanceBase.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritance_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritance_GsonTypeAdapter.java
=> Fixed bug which caused annotated interfaces to not allow inheritance

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/ModelInterfaceGenerator.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/InterfaceTest.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/invalid/TestValidInterface_ReturningVoid.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/invalid/TestValidInterface_WithParameters.java
=> Added better error handling for invalid interfaces

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/ModelInterfaceGenerator.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritance_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/primitive/TestUsingPrimitives.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/primitive/TestUsingPrimitives_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/primitive/TestUsingPrimitives_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/valid/TestValidInterface_GsonPathModel.java
=> Added equals and hashcode generation to interface generated pojos

gsonpath/src/main/java/gsonpath/FlattenDelimiter.java, gsonpath/src/main/java/gsonpath/FlattenJson.java
=> Allowed the FlattenJson annotation to be used on methods

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/AutoGsonAdapterGenerator.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/SubstitutionTest.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/errors/TestSubstitutionError_DuplicateKeys.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/valid/TestSubstitutionBase.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/valid/TestSubstitutionImpl1.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/valid/TestSubstitutionImpl1_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/valid/TestSubstitutionImpl2.java, gsonpath-compiler/src/test/resources/adapter/auto/substitution/valid/TestSubstitutionImpl2_GsonTypeAdapter.java, gsonpath/src/main/java/gsonpath/AutoGsonAdapter.java, gsonpath/src/main/java/gsonpath/PathSubstitution.java
=> Added path text substitution functionality

gsonpath-compiler/src/main/java/gsonpath/generator/BaseAdapterGenerator.java, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/InterfaceTest.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/flatten_json/TestFlattenJsonWithInterface.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/flatten_json/TestFlattenJsonWithInterface_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/flatten_json/TestFlattenJsonWithInterface_GsonTypeAdapter.java
=> Fixed crash caused by adding FlattenJson annotation to an interface

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/standard/ReadFunctions.kt
Further kotlin code quality improvements for readability and reuse.
=> Improved the code quality of the read functions

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/interf/ModelInterfaceGenerator.kt, gsonpath-compiler/src/test/resources/adapter/auto/generics/interfaces/GenericsTest_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/flatten_json/TestFlattenJsonWithInterface_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/inheritance/TestUsingInheritance_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/primitive/TestUsingPrimitives_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/valid/TestValidInterface.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/valid/TestValidInterface_GsonPathModel.java, gsonpath-compiler/src/test/resources/adapter/auto/interface_example/valid/TestValidInterface_GsonTypeAdapter.java
This resolves issue #74 which was a potential bug with variable name collisions.
=> Issue #74 - Fixed interface generated pojo local variable names

CHANGELOG.md, gsonpath-compiler/src/main/java/gsonpath/GsonProcessorImpl.kt, gsonpath-compiler/src/main/java/gsonpath/generator/adapter/factory/TypeAdapterFactoryGenerator.kt, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/factory/TypeAdapterFactoryGeneratorTest.kt, gsonpath-compiler/src/test/resources/adapter/loader/NonGsonPathFile.java, gsonpath-compiler/src/test/resources/adapter/loader/TestGsonTypeFactory2.java, gsonpath-compiler/src/test/resources/adapter/loader/TestGsonTypeFactoryAsClass.java, gsonpath-compiler/src/test/resources/adapter/loader/TestGsonTypeFactoryIncorrectInterfaces.java, gsonpath-compiler/src/test/resources/adapter/loader/TestGsonTypeFactoryNoInterfaces.java, gsonpath/src/main/java/gsonpath/AutoGsonAdapterFactory.java
Improved the documentation for the `@AutoGsonAdapterFactory` annotation, as well as adding better unit testing coverage, and more informative error messages.
=> Feature/improve 2.0.0 documentation

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/standard/SubtypeFunctions.kt, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/PolymorphismTest.kt, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/boolean_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/boolean_keys/TypesList_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/integer_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/integer_keys/TypesList_GsonTypeAdapter.java, gsonpath/src/main/java/gsonpath/GsonSubtype.java
Improved the GsonSubType feature by adding integer and boolean support.
This relates to issue #78
=> Issue #78 Added GsonSubType integer and boolean keys

gsonpath-compiler/src/main/java/gsonpath/generator/adapter/interf/ModelInterfaceGenerator.kt, gsonpath-compiler/src/main/java/gsonpath/generator/adapter/standard/SubtypeFunctions.kt, gsonpath-compiler/src/main/java/gsonpath/model/FieldInfo.kt, gsonpath-compiler/src/main/java/gsonpath/model/FieldInfoFactory.kt, gsonpath-compiler/src/main/java/gsonpath/model/InterfaceFieldInfo.kt, gsonpath-compiler/src/test/java/gsonpath/generator/adapter/auto/PolymorphismTest.kt, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/blank_field/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/boolean_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/duplicate_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/duplicate_keys/TypesList_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/integer_keys/TypesList_GsonTypeAdapter.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/multiple_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/no_keys/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/type_no_inheritance/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/using_interface/TypesList.java, gsonpath-compiler/src/test/resources/adapter/auto/polymorphism/using_interface/TypesList_GsonTypeAdapter.java
Improved the GsonSubType processor error messaging.
This is a WIP feature relating to issue #78
=> Issue #78 Improved GsonSubType processor error messaging

build.gradle, gsonpath-compiler-base/build.gradle, gsonpath-compiler/build.gradle, gsonpath-compiler/src/main/java/gsonpath/model/GsonObjectTreeFactory.kt, gsonpath-sample/build.gradle, gsonpath/build.gradle
Updated to dependencies in preparation for adding kotlin data class support in the future.
=> Updated to latest version of dependencies

.travis.yml, build.gradle
=> Issue #100 Added sonarcloud integration

gsonpath-compiler-base/src/main/java/gsonpath/model/FieldInfo.kt, gsonpath-compiler-tests/src/test/java/gsonpath/generator/standard/FieldValidationTypeTest.kt, gsonpath-compiler-tests/src/test/resources/generator/standard/field_policy/default_value/TestValidateWithDefaultValue.java, gsonpath-compiler-tests/src/test/resources/generator/standard/field_policy/default_value/TestValidateWithDefaultValue_GsonTypeAdapter.java, gsonpath-compiler/build.gradle, gsonpath-compiler/src/main/java/gsonpath/generator/standard/ReadFunctions.kt, gsonpath-compiler/src/main/java/gsonpath/model/FieldInfoFactory.kt, gsonpath-compiler/src/main/java/gsonpath/model/GsonObjectFactory.kt
=> Issue #113 Prevent POJOs fields with a default value throwing JsonFieldMissingException

gsonpath-compiler-tests/src/test/java/gsonpath/generator/standard/ProcessorErrorsTest.kt, gsonpath-compiler-tests/src/test/java/gsonpath/model/BaseGsonObjectFactoryTest.kt, gsonpath-compiler-tests/src/test/resources/generator/standard/processor_errors/TestSerializedNameAlternateUsedError.java, gsonpath-compiler/src/main/java/gsonpath/model/GsonObjectFactory.kt
=> Issue #121 Updated processor to fail on SerializedName alternate

gsonpath-compiler-tests/src/test/java/gsonpath/generator/standard/UseGetterAnnotationTest.kt, gsonpath-compiler-tests/src/test/resources/generator/standard/use_getter_annotation/UseGetterAnnotationTest.java, gsonpath-compiler-tests/src/test/resources/generator/standard/use_getter_annotation/UseGetterAnnotationTest_Implementation_GsonTypeAdapter.java, gsonpath-compiler/src/main/java/gsonpath/model/FieldInfoFactory.kt, gsonpath-sample/src/main/java/gsonpath/kotlin/SealedClassSample.kt, gsonpath-sample/src/test/java/gsonpath/kotlin/SealedClassSampleTest.java, gsonpath-sample/src/test/resources/SealedClassSample.json
=> Issue 137 fix kotlin sealed class

gsonpath-compiler-tests/src/test/java/gsonpath/generator/standard/PolymorphismTest.kt, gsonpath-compiler-tests/src/test/resources/generator/standard/polymorphism/with_other_elements/TypesList.java, gsonpath-compiler-tests/src/test/resources/generator/standard/polymorphism/with_other_elements/TypesList_GsonTypeAdapter.java, gsonpath-compiler/src/main/java/gsonpath/generator/standard/SubtypeFunctions.kt, gsonpath-sample/src/main/java/gsonpath/kotlin/SealedClassSample.kt
=> Issue #141 - Fixed GsonSubType when other fields defined prior

gsonpath-compiler/base/src/main/java/gsonpath/util/AnnotationFetcher.kt, gsonpath-compiler/testing/integration-standard/src/test/java/gsonpath/generator/standard/NestedJsonTest.kt, gsonpath-compiler/testing/integration-standard/src/test/resources/generator/standard/nested_json/field_nesting_autocomplete_inheritance/TestFieldNestingAutocomplete.java, gsonpath-compiler/testing/integration-standard/src/test/resources/generator/standard/nested_json/field_nesting_autocomplete_inheritance/TestFieldNestingAutocompleteBase.java, gsonpath-compiler/testing/integration-standard/src/test/resources/generator/standard/nested_json/field_nesting_autocomplete_inheritance/TestFieldNestingAutocomplete_GsonTypeAdapter.java
=> Issue #153 - Fixed method annotation inheritance for interfaces

gsonpath-core/compiler/standard/src/main/java/gsonpath/generator/adapter/subtype/SubtypeFunctions.kt, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/boolean_keys/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/default_value/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/duplicate_keys/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/failure_outcome_fail/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/failure_outcome_remove_element/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/integer_keys/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/string_keys/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/using_interface/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/using_list/TypesList_GsonTypeAdapter.java, gsonpath-core/compiler/testing/integration-standard/src/test/resources/generator/standard/polymorphism/with_other_elements/TypesList_GsonTypeAdapter.java, gsonpath-core/sample/src/main/java/gsonpath/polymorphism/Type.java, gsonpath-core/sample/src/test/java/gsonpath/polymorphism/PolymorphismTest.java
=> Issue #174 Do not remove subTypeKey when deserializing SubType

compiler/standard/src/main/java/gsonpath/adapter/common/GsonSubTypeFactory.kt, compiler/standard/src/main/java/gsonpath/adapter/common/SubTypeMetadataFactory.kt, compiler/testing/integration/src/test/java/gsonpath/adapter/standard/extension/GsonSubTypeExtensionTest.kt, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/boolean_keys/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/boolean_keys/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/default_value/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/default_value/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/failure_outcome_fail/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/failure_outcome_fail/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/failure_outcome_remove_element/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/integer_keys/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/integer_keys/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/null_string_key/TypeGsonSubType.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/null_string_key/TypesList.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/null_string_key/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/null_string_key/TypesPojo.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/null_string_key/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/string_keys/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/string_keys/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/using_interface/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/using_list/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/with_other_elements/TypesList_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/extension/gson_sub_type/with_other_elements/TypesPojo_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/gson_sub_type/directly_annotated/DirectlyAnnotatedSubType_GsonTypeAdapter.java, compiler/testing/integration/src/test/resources/generator/gson_sub_type/indirectly_annotated/IndirectlyAnnotatedSubType_GsonTypeAdapter.java, library/src/main/java/gsonpath/GsonSubtype.java, sample/src/main/java/gsonpath/adapter/standard/extension/gsonSubType/TypeGsonSubType.java, sample/src/main/java/gsonpath/adapter/standard/extension/gsonSubType/TypeNull.java, sample/src/test/java/gsonpath/adapter/standard/extension/gsonSubType/GsonSubTypeTest.java, sample/src/test/resources/Polymorphism_valid.json
=> Issue #210 Add nullable value support for GsonSubType

compiler/base/src/main/java/gsonpath/util/DefaultValueDetector.kt, compiler/base/src/main/java/gsonpath/util/SunTreesProvider.kt, compiler/standard/src/main/java/gsonpath/GsonProcessor.kt, compiler/standard/src/main/java/gsonpath/dependencies/DependencyFactory.kt, compiler/standard/src/main/resources/META-INF/gradle/incremental.annotation.processors, compiler/testing/integration/src/main/java/gsonpath/generator/GeneratorTester.kt, compiler/testing/integration/src/test/java/gsonpath/adapter/subType/SubTypeTest.kt, compiler/testing/integration/src/test/java/gsonpath/generator/standard/CustomAutoGsonAdapterTest.kt, sample/build.gradle, sample/src/main/java/gsonpath/kotlin/CustomAnnotation.kt, sample/src/main/java/gsonpath/kotlin/DataClassSample.kt
Made the processor aggregating after a large amount of trial and error.
I originally had planned to split the processor into two. The majority of the work being done using an Isolating processor, and the factories being generated using an Aggregating processor.
It turns out that this won't work, as there is a chance that the factories are not in the correct state when changes are made.
The safest approach is to make the entire processor aggregating for now.
=> Issue #227 Added incremental processing

library-kt/src/main/java/gsonpath/result/GsonResult.kt, library-kt/src/main/java/gsonpath/result/GsonResultListTypeAdapterFactory.kt
=> Issue 248 improve gsonresult failure exception

compiler/standard/src/main/java/gsonpath/adapter/enums/EnumGsonAdapterGenerator.kt, compiler/standard/src/test/resources/generator/enums/with_default/TestEnumWithDefault_GsonTypeAdapter.java, library/src/main/java/gsonpath/audit/AuditJsonReader.java, library/src/main/java/gsonpath/audit/AuditLog.java, library/src/main/java/gsonpath/extension/RemoveInvalidElementsUtil.java, sample/src/main/java/gsonpath/adapter/enums/EnumExample.kt, sample/src/main/java/gsonpath/errors/GsonErrorTestModel.java, sample/src/test/java/gsonpath/TestUtil.kt, sample/src/test/java/gsonpath/adapter/enums/EnumExampleTests.kt, sample/src/test/java/gsonpath/errors/GsonErrorTestModelTest.kt, sample/src/test/resources/EnumJson.json, sample/src/test/resources/GsonErrorTestJson.json
=> Issue 263 add audit log

compiler/standard/src/main/java/gsonpath/adapter/enums/EnumAdapterPropertiesFactory.kt, compiler/standard/src/main/java/gsonpath/adapter/enums/EnumGsonAdapterGenerator.kt, compiler/standard/src/test/java/gsonpath/adapter/enums/EnumAdapterPropertiesFactoryTest.kt, compiler/standard/src/test/resources/generator/enums/without_default/TestEnumWithoutDefault.java, library/src/main/java/gsonpath/annotation/EnumGsonAdapter.java, sample/src/main/java/gsonpath/adapter/enums/EnumExample.kt
Add a compiler error for unexpected default enum values.
=> Issue #253 Add compiler error for unexpected default enums
